### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by jpettitt** [subscriptions-project/swg-js#1016]
Right now swg.js tends to just `throw new Error(...)` when something fails.  This is causing a problem with amp integration as it doesn't fit the AMP error handling model.  [AMP issue 27223](https://github.com/ampproject/amphtml/issues/27223).

We should use a standard error handler that can be replaced with the AMP one in the similarly to the way we handle `fetch`

**Comment by rcebulko** [comment]
If you'd like, I could port a simplified version `user().error(args)`, `user().expectedError(args)`, `dev().error(args)`, and `dev().expectedError(args)` into SwG that just adds the sentinel values/`expected` property and throws

**Comment by jpettitt** [comment]
That would be great - I'd rather not have the sentinels unless it's in an amp context so maybe detect the AMP global before adding them?

**Comment by rcebulko** [comment]
I can't request your review, but the above PR adds an error logger interface
