### ISSUE TITLE
Get gpay sync to swg-js/third_party working again

### ISSUE THREAD

**Issue by elijahsoria** [subscriptions-project/swg-js#1177]
The swg-js/third_party/gpay code is currently out of date due to the sync between https://github.com/google/payjs and swg-js not working properly.

Issue created to track the process of getting third_party/gpay code up to date again and to track the sync development.

**Comment by alin04** [comment]
Although github payjs itself is also out of sync from its source of truth....

**Comment by fikus** [comment]
Tracked in internal bug b/178416993 with more detail.
