### ISSUE TITLE
Bump SwG Version number when we switch to article endpoint

### ISSUE THREAD

**Issue by jpettitt** [subscriptions-project/swg-js#2078]
When #2035 is 100% I'd like to bump the SwG.js version from 1.22.xxx to 1.23.0 a minor version in the 200's is getting ridiculous.

cc @alin04 @mmmicedcoffee @hartmannr76 @adolgachev @cfa

**Comment by hartmannr76** [comment]
Makes sense to me 👍

**Comment by ChrisAntaki** [comment]
Sounds good :+1:

**Comment by jpettitt** [comment]
Where are we on this?

**Comment by hartmannr76** [comment]
This has been running at 100% with no reported issues. Looks like we should be safe to bump the version

**Comment by ChrisAntaki** [comment]
Updated ✔️  
https://github.com/subscriptions-project/swg-js/releases/tag/1.0.0
