### ISSUE TITLE
Try moving from custom logic for ESM output to Rollup Plugin

### ISSUE THREAD

**Issue by kristoferbaxter** [subscriptions-project/swg-js#375]
https://github.com/subscriptions-project/swg-js/blob/master/build-system/tasks/export-to-es.js#L43

Rollup is used to build the ESM output format, we should try using the rollup closure compiler plugin to output this code without manual replacements post minification.

https://github.com/ampproject/rollup-plugin-closure-compiler/tree/externals, you'll want to use the alpha release like other projects are.

`"@ampproject/rollup-plugin-closure-compiler": "0.5.0-alpha.2",`

**Comment by jpettitt** [comment]
Looks like the first pass at fixing this didn't quite work.  I had to disable comment remove to get AMP to build with the new code as it was failing `gulp check-types`.  @kristoferbaxter suggests we need to add an externs file.  See https://github.com/ampproject/amphtml/pull/17199
